spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/datajpa
      username: sa
      password:
      driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

  # paging global setting
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000 # default 2000
#        one-indexed-parameters: true # setting page start 1 (default: false) => pageable number limit

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace
